import { createServiceClient } from "@/lib/supabase/server";
import { notFound } from "next/navigation";
import Link from "next/link";
import type { Metadata } from "next";

type ConversationMessage = { role: "user" | "assistant"; content: string };

interface SharePageProps {
  params: Promise<{ uuid: string }>;
}

export async function generateMetadata({
  params,
}: SharePageProps): Promise<Metadata> {
  const { uuid } = await params;
  const admin = createServiceClient();
  const { data } = await admin
    .from("fit_conversations")
    .select("summary")
    .eq("id", uuid)
    .eq("share_enabled", true)
    .maybeSingle();

  return {
    title: "Fit Concierge Consultation, Tempo",
    description:
      data?.summary ??
      "A shared Tempo AI Fit Concierge consultation for adaptive fashion.",
  };
}

export default async function SharePage({ params }: SharePageProps) {
  const { uuid } = await params;
  const admin = createServiceClient();

  const { data } = await admin
    .from("fit_conversations")
    .select("id, messages, summary, created_at")
    .eq("id", uuid)
    .eq("share_enabled", true)
    .maybeSingle();

  if (!data) notFound();

  const messages = data.messages as unknown as ConversationMessage[];
  const createdAt = new Date(data.created_at as string).toLocaleDateString(
    "en-US",
    { year: "numeric", month: "long", day: "numeric" }
  );

  return (
    <main className="max-w-2xl mx-auto px-4 py-12">
      <div className="mb-8">
        <Link
          href="/shop"
          className="text-sm text-[#7A8B75] hover:text-[#5a6b55] underline underline-offset-4 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#C29E5F] rounded"
        >
          Browse Tempo adaptive clothing
        </Link>
      </div>

      <div className="mb-2">
        <span className="text-xs bg-[#C29E5F]/20 text-[#C29E5F] border border-[#C29E5F]/40 px-2 py-0.5 rounded-full font-medium">
          Shared consultation
        </span>
      </div>

      <h1 className="font-playfair text-2xl font-bold text-[#1A1A1A] mt-3 mb-1">
        Fit Concierge Consultation
      </h1>
      <p className="text-sm text-[#9A9A9A] mb-8">{createdAt}</p>

      {data.summary && (
        <section
          aria-labelledby="summary-heading"
          className="bg-[#E8DFD2] border border-[#D4C9BA] rounded-xl p-6 mb-8"
        >
          <h2
            id="summary-heading"
            className="text-xs font-semibold uppercase tracking-wide text-[#9A9A9A] mb-3"
          >
            Clinical summary
          </h2>
          <p className="text-sm text-[#1A1A1A] leading-relaxed">
            {data.summary as string}
          </p>
        </section>
      )}

      <section aria-labelledby="transcript-heading">
        <h2
          id="transcript-heading"
          className="text-xs font-semibold uppercase tracking-wide text-[#9A9A9A] mb-4"
        >
          Full transcript
        </h2>
        <div className="space-y-4">
          {messages.map((msg, i) => (
            <div
              key={i}
              className={`rounded-xl p-4 text-sm leading-relaxed ${
                msg.role === "user"
                  ? "bg-[#E8DFD2] border border-[#D4C9BA] text-[#1A1A1A] ml-8"
                  : "bg-[#FAFAF7] border border-[#D4C9BA] text-[#5A5A5A] mr-8"
              }`}
            >
              <span className="font-medium text-xs uppercase tracking-wide text-[#9A9A9A] block mb-1.5">
                {msg.role === "user" ? "Customer" : "Fit Concierge"}
              </span>
              <span className="whitespace-pre-wrap">{msg.content}</span>
            </div>
          ))}
        </div>
      </section>

      <footer className="mt-12 pt-6 border-t border-[#D4C9BA] text-center">
        <p className="text-xs text-[#9A9A9A] mb-3">
          This consultation was generated by Tempo&apos;s AI Fit Concierge. All
          product recommendations are based on the information provided.
        </p>
        <Link
          href="/shop"
          className="inline-block text-sm font-medium px-5 py-2.5 rounded-lg bg-[#7A8B75] text-white hover:bg-[#6a7a65] motion-safe:transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#C29E5F]"
        >
          Shop adaptive clothing
        </Link>
      </footer>
    </main>
  );
}
